apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docfactory-monitoring.fullname" . }}
  labels:
    {{- include "docfactory-monitoring.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docfactory-monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docfactory-monitoring.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docfactory-monitoring.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "docfactory-monitoring.fullname" . }}-db-credentials
          volumeMounts:
            - name: queries-config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: queries-config
          configMap:
            name: {{ include "docfactory-monitoring.fullname" . }}-queries 