{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "docfactory-monitoring.fullname" . }}-db-credentials
  labels:
    {{- include "docfactory-monitoring.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "docfactory-monitoring.fullname" . }}-db-credentials
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.vault.path }}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.vault.path }}
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecrets.vault.path }}
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.vault.path }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vault.path }}
        property: DB_PASSWORD
{{- end }} 