{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    vault:
      server: "http://vault.vault-system:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vault.auth.mountPath }}
          role: {{ .Values.externalSecrets.vault.auth.role }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.vault.auth.serviceAccount.name }}
{{- end }} 